# Generated by Django 5.0.7 on 2026-01-28 07:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_staffprofile_staffattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(help_text='Customer name for this bill', max_length=200)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone for this bill', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Total before discount and tax', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated discount amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Tax/GST percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated tax amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Final total amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('credit', 'Credit'), ('other', 'Other')], db_index=True, default='cash', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount received from customer', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, help_text='Remaining amount (can be negative for change)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for refund')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('refund_date', models.DateTimeField(auto_now_add=True)),
                ('original_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='medical.bill')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('refund_bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_for', to='medical.bill')),
            ],
            options={
                'ordering': ['-refund_date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True)),
                ('doctor_name', models.CharField(blank=True, help_text="Prescribing doctor's name", max_length=200)),
                ('prescription_number', models.CharField(blank=True, help_text='Prescription reference number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='medical_cus_phone_9dbd70_idx'), models.Index(fields=['name'], name='medical_cus_name_1b72e1_idx')],
                'unique_together': {('phone', 'name')},
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Linked customer record (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='medical.customer'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('credit', 'Credit'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_reference', models.CharField(blank=True, help_text='Cheque number, UPI ID, etc.', max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='medical.bill')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(help_text='Medicine name at time of sale', max_length=200)),
                ('batch_number', models.CharField(help_text='Batch number at time of sale', max_length=100)),
                ('quantity', models.IntegerField(help_text='Quantity sold', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of sale', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this item (quantity × unit_price)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(help_text='Parent bill', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical.bill')),
                ('medicine', models.ForeignKey(help_text='Medicine being sold (protected from deletion)', on_delete=django.db.models.deletion.PROTECT, to='medical.medicine')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['bill', 'medicine'], name='medical_bil_bill_id_5e137e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_number'], name='medical_bil_bill_nu_29126b_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status', 'created_at'], name='medical_bil_status_b11ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['payment_method', 'created_at'], name='medical_bil_payment_f1e319_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['customer', 'created_at'], name='medical_bil_custome_51c336_idx'),
        ),
    ]
